name: domain
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  json_annotation: ^4.4.0

dev_dependencies:
  lints: ^1.0.0
  build_runner:
  json_serializable:
